version: "3.8"
services:
  prochat-redis:
    container_name: prochat-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: tztos104/prochat-redis
    ports:
      - "6379:6379"

  prochat-database:
    container_name: prochat-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: tztos104/prochat-database

    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: prochat

    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/config:/docker-entrypoint-initdb.d
  prochat-jenkins:
    container_name: prochat-jenkins
    build:
      dockerfile: Dockerfile
      context: ./jenkins
    restart: unless-stopped
    user: root
    ports:
      - 8888:8080
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - ./jenkins/.ssh:/root/.ssh

      # 다른 설정들 추가
volumes:
  jenkins_data: